config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {registrations: 'registrations'}
  resources :assignments
  resources :games
  resources :users, :only =>[:show]
  

  root "home#show"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/assignment.rb
class Assignment < ApplicationRecord
    belongs_to :game
    

    belongs_to :center_referee, class_name: 'User', optional: true
    belongs_to :assistant_referee_1, class_name: 'User', optional: true
    belongs_to :assistant_referee_2, class_name: 'User', optional: true
    belongs_to :fourth_official, class_name: 'User', optional: true

    accepts_nested_attributes_for :game    

    
    

    def center
        User.where(id: center_referee_id).map { |user| user.name }
    end
    
    def ar1
        User.where(id: assistant_referee_1_id).map { |user| user.name }
    end
    
    def ar2
        User.where(id: assistant_referee_2_id).map { |user| user.name }
    end

    def fourth
        User.where(id: fourth_official_id).map { |user| user.name }
    end
end

app/models/game.rb
class Game < ApplicationRecord
    has_one :assignment
    has_many :users, through: :assignment

    after_create :create_assignment    

    def create_assignment
    Assignment.create!(game_id: id)
    end

    def teams
        teams = "#{home_team} vs #{away_team}"
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :assignments
  has_many :games, through: :assignments

  def name
    name = "#{first_name&.capitalize} #{last_name&.capitalize} "
  end

  def written_address
    written_address = "#{address["city"]}, #{address["state"]}, #{address["zip_code"]}"
  end


  def assigned_games
    Game.joins(:assignment).where('assignments.center_referee_id = ? OR assignments.assistant_referee_1_id = ? OR assignments.assistant_referee_2_id = ? OR assignments.fourth_official_id = ?', id, id, id, id).map { |game| game.teams}
  end


  def formatted_cell_phone
    parsed_phone = Phonelib.parse(cell_phone)
    return cell_phone if parsed_phone.invalid?

    formatted =
      if parsed_phone.country_code == "1"
        parsed_phone.full_national
      else
        parsed_phone.full_international
      end
    formatted.gsub!(";", " x")
    formatted
  end

  def formatted_work_phone
    parsed_phone = Phonelib.parse(work_phone)
    return work_phone if parsed_phone.invalid?

    formatted =
      if parsed_phone.country_code == "1"
        parsed_phone.full_national
      else
        parsed_phone.full_international
      end
    formatted.gsub!(";", " x")
    formatted
  end

  def formatted_home_phone
    parsed_phone = Phonelib.parse(home_phone)
    return home_phone if parsed_phone.invalid?

    formatted =
      if parsed_phone.country_code == "1"
        parsed_phone.full_national
      else
        parsed_phone.full_international
      end
    formatted.gsub!(";", " x")
    formatted
  end

  def normalize_phone
    self.cell_phone = Phonelib.parse(cell_phone).full_e164.presence
    self.work_phone = Phonelib.parse(work_phone).full_e164.presence
    self.home_phone = Phonelib.parse(home_phone).full_e164.presence
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/assignments_controller.rb
class AssignmentsController < ApplicationController
  before_action :set_assignment, only: %i[ show edit update destroy ]

  # GET /assignments or /assignments.json
  def index
    @assignments = Assignment.all
  end

  # GET /assignments/1 or /assignments/1.json
  def show
  end

  # GET /assignments/new
  def new
    @assignment = Assignment.new
  end

  # GET /assignments/1/edit
  def edit
  end

  # POST /assignments or /assignments.json
  def create
    @assignment = Assignment.new(assignment_params)

    respond_to do |format|
      if @assignment.save
        format.html { redirect_to @assignment, notice: "Assignment was successfully created." }
        format.json { render :show, status: :created, location: @assignment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @assignment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /assignments/1 or /assignments/1.json
  def update
    respond_to do |format|
      if @assignment.update(assignment_params)
        format.html { redirect_to @assignment, notice: "Assignment was successfully updated." }
        format.json { render :show, status: :ok, location: @assignment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @assignment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /assignments/1 or /assignments/1.json
  def destroy
    @assignment.destroy
    respond_to do |format|
      format.html { redirect_to assignments_url, notice: "Assignment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_assignment
      @assignment = Assignment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def assignment_params
      params.require(:assignment).permit(:game_id, :center_referee_id, :assistant_referee_1_id, :assistant_referee_2_id, :fourth_official_id)
    end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: %i[ show edit update destroy ]

  # GET /games or /games.json
  def index
    @games = Game.all
  end

  # GET /games/1 or /games/1.json
  def show
  end

  # GET /games/new
  def new
    @game = Game.new
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games or /games.json
  def create
    @game = Game.new(game_params)

    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: "Game was successfully created." }
        format.json { render :show, status: :created, location: @game }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1 or /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to @game, notice: "Game was successfully updated." }
        format.json { render :show, status: :ok, location: @game }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1 or /games/1.json
  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url, notice: "Game was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def game_params
      params.require(:game).permit(:home_team, :away_team, :start_time, :end_time)
    end

    def update_game_params
      params.require(:game).permit(:home_team, :away_team, :start_time, :end_time)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def show
        @games = Game.all
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
    private
    
      def sign_up_params
        params.require(:user).permit(
          :email,
          :password,
          :password_confirmation,
          :cell_phone,
          :work_phone,
          :home_phone,
          address: [:street_address, :city, :state, :zip])
      end
    
      def account_update_params
        params.require(:user).permit(
          email,
          :password,
          :password_confirmation,
          :current_password,
          :cell_phone,
          :work_phone,
          :home_phone,
          address: [:street_address, :city, :state, :zip])
      end
      
    end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @games = Game.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/assignments_helper.rb
module AssignmentsHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/assignments/_form.html.erb
<div class="flex flex-col items-center h-screen my-32">
  <div class="w-full max-w-lg ">
    <div class="px-8 pt-6 pb-8 mb-4 bg-white rounded shadow-md">
      <div class="mb-4">
        <%= simple_form_for(@assignment) do |f| %>
          <%= f.error_notification %>
          <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
          <div class="mb-6">
            <label class="block mb-2 text-sm font-bold text-gray-700">Editing Assignment for:<Br> <%= @assignment.game.teams %></label>
            
            <label class="block mb-2 text-sm font-bold text-gray-700" for="username">Center:</label>
                <%= f.input :center_referee, label: false do %>
                    <%= f.select :center_referee_id, User.all.map { |r| [r.name, r.id] }, {include_blank: "Select Referee"}, {class:"shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" } %>
                <% end %>       
          </div>
          <div class="mb-6">
            <label class="block mb-2 text-sm font-bold text-gray-700" for="username">Assistant Referee 1:</label>
                <%= f.input :assistant_referee_1_id, label: false do %>
                    <%= f.select :assistant_referee_1_id, User.all.map { |r| [r.name, r.id] }, {include_blank: "Select Referee"}, {class:"shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" } %>
                <% end %>       
            </div>
            <div class="mb-6">
            <label class="block mb-2 text-sm font-bold text-gray-700" for="username">Assistant Referee 2:</label>
                <%= f.input :assistant_referee_2_id, label: false do %>
                    <%= f.select :assistant_referee_2_id, User.all.map { |r| [r.name, r.id] }, {include_blank: "Select Referee"}, {class:"shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" } %>
                <% end %>       
            </div>
            <div class="mb-6">
            <label class="block mb-2 text-sm font-bold text-gray-700" for="username">Fourth Official:</label>
                <%= f.input :fourth_official, label: false do %>
                    <%= f.select :fourth_official_id, User.all.map { |r| [r.name, r.id] }, {include_blank: "Select Referee"}, {class:"shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" } %>
                <% end %>       
            </div>
            <div class="flex items-center justify-between">
                <%= f.button :submit, "Update Assignment", class:"px-4 py-2 font-bold w-full text-white bg-blue-500 rounded hover:bg-blue-700 focus:outline-none focus:shadow-outline"  %>
            </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/assignments/edit.html.erb
<%= render 'form', assignment: @assignment %>

<%= link_to 'Show', @assignment %> |
<%= link_to 'Back', assignments_path %>

app/views/assignments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Assignments</h1>

<table>
  <thead>
    <tr>
      <th>Game</th>
      <th>Center referee</th>
      <th>Assistant referee 1</th>
      <th>Assistant referee 2</th>
      <th>Fourth official</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @assignments.each do |assignment| %>
      <tr>
        <td><%= assignment.game.teams %></td>
        <td><%= assignment.center[0] %></td>
        <td><%= assignment.ar1[0] %></td>
        <td><%= assignment.ar2[0] %></td>
        <td><%= assignment.fourth[0] %></td>
        <td><%= link_to 'Show', assignment %></td>
        <td><%= link_to 'Edit', edit_assignment_path(assignment) %></td>
        <td><%= link_to 'Destroy', assignment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/assignments/new.html.erb
<h1>New Assignment</h1>

<%= render 'form', assignment: @assignment %>

<%= link_to 'Back', assignments_path %>

app/views/assignments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Game:</strong>
  <%= @assignment.game.teams %>
</p>

<p>
  <strong>Center referee:</strong>
  <%= @assignment.center[0] %>
</p>

<p>
  <strong>Assistant referee 1:</strong>
  <%= @assignment.ar1[0] %>
</p>

<p>
  <strong>Assistant referee 2:</strong>
  <%= @assignment.ar2[0]  %>
</p>

<p>
  <strong>Fourth official:</strong>
  <%= @assignment.fourth[0] %>
</p>

<%= link_to 'Edit', edit_assignment_path(@assignment) %> |
<%= link_to 'Back', assignments_path %>

app/views/games/_form.html.erb
<div class="flex flex-col items-center h-screen my-32">
  <div class="w-full max-w-lg ">
    <div class="px-8 pt-6 pb-8 mb-4 bg-white rounded shadow-md">
      <div class="mb-4">
        <%= simple_form_for(@game) do |f| %>
          <%= f.error_notification %>
          <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
          <div class="mb-6">
            <label class="block mb-2 text-sm font-bold text-gray-700" for="username">Home Team</label>
              <%= f.input :home_team,
                  label:false, 
                  input_html: {class:"shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" } %>
          </div>
          <div class="mb-6">
            <label class="block mb-2 text-sm font-bold text-gray-700" for="username">Away Team</label>
              <%= f.input :away_team,
                  label:false, 
                  input_html: {class:"shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" } %>
          </div>
          <div class="mb-6">
            <label class="block mb-2 text-sm font-bold text-gray-700" for="username">Start Time</label>
              <%= f.input :start_time,
                  label:false,
                  default: Time.parse('12:00'),
                  minute_step: 15,
                  :ampm => true,
                  order: %i(month day year),
                  input_html: {class:"shadow appearance-none border rounded w-22 py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" } %>

          </div>
          <div class="mb-6">
            <label class="block mb-2 text-sm font-bold text-gray-700" for="username">End Time</label>
              <%= f.input :end_time, 
                  label:false,
                  default: Time.parse('14:00'),
                  minute_step: 15,
                  :ampm => true,
                  order: %i(month day year),
                  input_html: {class:"shadow appearance-none border rounded w-22 py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" } %>
          </div>
          <div class="flex items-center justify-between">
            <%= f.button :submit, "Create Game", class:"px-4 py-2 font-bold w-full text-white bg-blue-500 rounded hover:bg-blue-700 focus:outline-none focus:shadow-outline"  %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/games/edit.html.erb
<h1>Editing Game</h1>

<%= render 'form', game: @game %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Games</h1>

<div>
    <% @games.each do | game | %>
        <%= link_to game do %>
            <p><%= game.home_team %> vs <%= game.away_team %></p>
        <% end %>
        <p><%= game.start_time.strftime("%b %d, %Y %I:%M%P")  %> - <%= game.end_time.strftime("%I:%M%P")  %></p>
        <br>
        <p><%= link_to 'Show', game %></p>
        <p><%= link_to 'Edit', edit_game_path(game) %></p>
        <p><%= link_to 'Destroy', game, method: :delete, data: { confirm: 'Are you sure?' } %></p>
    <% end %>
</div>

<br>
<%= link_to 'New Game', new_game_path %>

app/views/games/new.html.erb
<%= render 'form', game: @game %>

app/views/games/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Home team:</strong>
  <%= @game.home_team %>
</p>

<p>
  <strong>Away team:</strong>
  <%= @game.away_team %>
</p>

<p>
  <strong>Start time:</strong>
  <%= @game.start_time.strftime("%l:%M%P")%>
</p>

<p>
  <strong>End time:</strong>
  <%= @game.end_time.strftime("%l:%M%P") %>
</p>
<br>

<p>
  <strong>Crew Assignments</strong>
  
</p>


<p><strong>Center: </strong> <%= @game.assignment.center_referee&.name %></p>
<p><strong>AR1: </strong> <%= @game.assignment.assistant_referee_1&.name %></p>
<p><strong>AR2: </strong> <%= @game.assignment.assistant_referee_2&.name %></p>
<p><strong>4th: </strong> <%= @game.assignment.fourth_official&.name %></p>
<br>

<%= link_to 'Edit', edit_game_path(@game) %> |
<%= link_to 'Back', games_path %> |
<%= link_to 'Assignment', edit_assignment_path(@game) %> 

app/views/home/show.html.erb
<div class="m-20">


<div>
    <% @games.each do | game | %>
        <%= link_to game do %>
            <p><%= game.home_team %> vs <%= game.away_team %></p>
        <% end %>
        <p><%= game.start_time.strftime("%b %d, %Y %I:%M%P")  %> - <%= game.end_time.strftime("%I:%M%P")  %></p>
        <br>
        
    <% end %>
</div>

<div class="mb-32">
<%= month_calendar(events: @games) do |date, games| %>
	<h1><%= date.day %></h1>

	<% games.each do |game| %>
		<%= link_to game do %>
			<h1 class="text-center text-blue-500"><%= game.teams %></h1>
            
        <% end %>
	<% end %>
<% end %>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RefSphereSystem</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <style>
      #menu-toggle:checked + #menu {
        display:block;
      }
    </style>
  </head>

  <body class="antialiased bg-gray-200">
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <header class="flex flex-wrap items-center px-6 py-2 bg-gray-700 lg:px-16 lg:py-0">
      <div class="flex items-center justify-between flex-1">
        <%= link_to root_path do %>
        <h1 class="flex items-center justify-between flex-1 text-2xl text-white">
            RefSphere
        </h1>
        <% end %>
      </div>

        <label for="menu-toggle" class="block cursor-pointer lg:hidden">
          <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-menu-2" width="32" height="32" viewBox="0 0 20 20" stroke-width="1.5" stroke="#ffbf00" fill="none" stroke-linecap="round" stroke-linejoin="round">
            <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
            <line x1="4" y1="6" x2="20" y2="6" />
            <line x1="4" y1="12" x2="20" y2="12" />
            <line x1="4" y1="18" x2="20" y2="18" />
          </svg>
        </label>
        <input type="checkbox" class="hidden" id="menu-toggle" />

        <div class="hidden w-full lg:flex lg:items-center lg:w-auto" id="menu">
          <nav>
            <ul class="items-center justify-between pt-4 text-base text-white lg:flex lg:pt-0">
              <li>
                <%= link_to root_path, class:"lg:p-4 py-3 px-0 block border-b-2 border-transparent hover:border-orange-500" do %>
                  <h1>Home</h1>
                <% end %>
              </li>
              <li>
                <%= link_to games_path, class:"lg:p-4 py-3 px-0 block border-b-2 border-transparent hover:border-orange-500" do %>
                  <h1>Games</h1>
                <% end %>
              </li>
              <li>
                <%= link_to root_path, class:"lg:p-4 py-3 px-0 block border-b-2 border-transparent hover:border-orange-500" do %>
                  <h1>Schedule</h1>
                <% end %>
              </li>
              <li>
                <%= link_to root_path, class:"lg:p-4 py-3 px-0 block border-b-2 border-transparent hover:border-orange-500" do %>
                  <h1>Availability</h1>
                <% end %>
              </li>
              <li>
                <%= link_to new_user_session_path, class:"lg:p-4 py-3 px-0 block border-b-2 border-transparent hover:border-orange-500" do %>
                  <h1>Sign In</h1>
                <% end %>
              </li>
              <% if user_signed_in? %>
              <li>
                <%= link_to current_user, class:"lg:p-4 py-3 px-0 block border-b-2 border-transparent hover:border-orange-500" do %>
                  <h1>Profile</h1>
                <% end %>
              </li>
              <li>
                <%= link_to destroy_user_session_path, method: :delete, class:"lg:p-4 py-3 px-0 block border-b-2 border-transparent hover:border-orange-500" do %>
                  <h1>Sign Out</h1>
                <% end %>
              </li>
              <% end %>
              
            </ul>
          </nav>
          <a href="#" class="flex items-center justify-start mb-4 cursor-pointer lg:ml-4 lg:mb-0">
            <img src="https://cbsnews3.cbsistatic.com/hub/i/r/2019/08/14/fdb57460-b0a7-4298-b25d-f58309048548/thumbnail/620x413/45e28f81a749aaa20eeb409393ed45c5/gettyimages-1168042139.jpg" class="w-10 h-10 border-2 border-transparent rounded-full hover:border-red-500" alt="name">
          </a> 
        </div>
      </div>
      
    </header>



    
    <%= yield %>
  </body>
</html>

app/views/users/show.html.erb
<div class="z-0 w-full py-40 pt-32 pb-20 bg-black"></div>
<div class="inline-flex">
    <img src="https://steamcdn-a.akamaihd.net/steamcommunity/public/images/avatars/b5/b51e51af5415ed472b9a0b4528baa46151ec95c6_full.jpg" 
    class="w-48 h-48 -mt-24 border-solid rounded-full border-sky-300 border-6 ml-80">
    <div>
        <h1 class="pt-4 pl-4 text-2xl text-left"><%= current_user.name %></h1>
        <h1 class="pt-2 pl-4 text-sm text-left text-red-500">REFEREE GRADE HERE</h1>
    </div>
</div>


<% current_user.assigned_games.each do |game| %>
    <p><%= game %></p>
<% end %>